apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-websocket
  name: kafka-websocket
spec:
  type: LoadBalancer
  ports:
    - name: "8766"
      port: 8766
      targetPort: 8766
  selector:
    io.kompose.service: kafka-websocket
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-websocket
  name: kafka-websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-websocket
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-websocket
    spec:
      containers:
        - image: shane233/kafka-websocket:latest 
          name: kafka-websocket
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
status: {}
